Wdp210402-11:addind favourites products
kamilwilk95/wdp-2104-02 pull request #12
Opened 2021-04-15 20:52 UTC by MarcinPytlak

2021-04-16 05:28 UTC, kamilwilk95 requested changes

2021-04-16 05:28 UTC, kamilwilk95 commented on src/redux/favouriteRedux.js
> +/* selectors */
Funkcjonalność dodawania produktów do ulubionych przeważnie jest bardzo prosta na stronach, jest ulubiony albo nie, w związku z tym nie ma potrzeby aby tworzyć całkowicie osobną logikę i domenę na potrzeby tej jeden funkcjonalności. W efekcie info o tym czy produkt jest ulubiony czy nie jest zwracane wraz z produktami, w postaci `boolean`. 

W naszym przypadku nie widzę powodu aby sobie to komplikować i trzymać favorite w całkowicie osobnym obiekcie stora, bo nie daje nam to żadnych dodatkowych plusów a tylko komplikuje cały kod.

Proponuje dodać po prostu pole `isFavourite: true | false` do produktów ;)

2021-04-16 05:28 UTC, kamilwilk95 commented on src/components/common/Button/Button.module.scss
> +  background-color: $text-color;
Z opisu taska: `Ulubione produkty mają mieć ten guzik zawsze taki jak na hover (kremowy)`

2021-04-17 12:21 UTC, MarcinPytlak commented
Hej Kamil, słuchaj, ja wiem, że się z Martyną dubluje tymi stylami, ale ja mam że ten button ma być taki jak na hover, a na hover mam czarny. tak to zrozumiałem, na razie tak to zostawiam, najważniejsza funkcjonalność :)

2021-04-17 14:18 UTC, kamilwilk95 requested changes

2021-04-17 14:18 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBox.js
> +  isFavourite,
Wywala błąd teraz bo brakuje `oldPrice`

2021-04-17 14:18 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBoxContainer.js
> +  products: getAll(state),
nie widzę aby `products` były wykorzystywane

2021-04-17 14:18 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBoxContainer.js
> +export default connect(mapStateToProps, mapDispatchToProps)(ProductBox);
Wydaje mi się że `Container` jest zbędny, ten komponent `ProductBox` niech zależy tylko od propsów

2021-04-17 17:54 UTC, kamilwilk95 requested changes

2021-04-17 17:54 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBox.js
> +          onClick={() => addFavourite({ id: id, isFavourite: !isFavourite })}
Jeszcze jeden problem, po kliknięciu strona skacze do góry, brakuje tutaj preventDefault?

2021-04-17 18:21 UTC, MarcinPytlak commented on src/components/common/ProductBox/ProductBox.js
> +          onClick={() => addFavourite({ id: id, isFavourite: !isFavourite })}
Tak jest, masz rację :) już dodane :)

2021-04-18 08:52 UTC, kamilwilk95 requested changes

2021-04-18 08:52 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBox.js
> +            addFavourite({ id: id, isFavourite: !isFavourite }) &&
a czemu tutaj jest taki dziwny zapis? Dlaczego wywołanie `preventDefault` jest uzależnione od tego czy `addFavourite` zwróci wartość true? W takich sytuacjach, najlepiej napisać osobną funkcję powyżej return np `onClickAddFavourite` i tam wszystko wywołać po koli standardowo, czyli najpierw prevent później add

2021-04-18 18:37 UTC, kamilwilk95 approved these changes

2021-04-18 18:37 UTC, merged