Wdp210402 14
kamilwilk95/wdp-2104-02 pull request #15
Opened 2021-04-16 19:56 UTC by stiffelbo

Mam nadzieje ze dobrze zrozumiałem zadanie.

Jak pisalem w JIRZE przy hoverze pływa mi nieco ikonka hamburgera, kompensowałem pozycionowaniem ale nie specjalnie mi sie podoba to rozwiązanie. Proszę o uwagi. Dzieki za review

2021-04-16 21:14 UTC, kamilwilk95 requested changes
![image](https://user-images.githubusercontent.com/26415481/115084473-44a33200-9f09-11eb-848b-1fd19e362c6b.png)
![image](https://user-images.githubusercontent.com/26415481/115084568-67cde180-9f09-11eb-981d-aeabd16ab347.png)
![image](https://user-images.githubusercontent.com/26415481/115084667-7ddba200-9f09-11eb-9e29-a3e163eea12d.png)

2021-04-16 21:14 UTC, kamilwilk95 commented on src/components/layout/MenuBar/MenuBar.js
> +            <FontAwesomeIcon className={styles.icon} icon={faBars} />
Ikona nie powinna być w liście `ul`, w liście mogą być tylko i wyłącznie elementy `li` a w nich dopiero coś innego.

Wyjęcie ikony poza menu powinno też rozwiązać problem z "pływaniem" po hover

2021-04-17 10:57 UTC, stiffelbo commented
Poprawiłem mobilne menu, ikonka już nie pływa, ale wciąż menu nie środkuje sie do hamburgera,  jest ustawione  pozycjonowaniem. Wyśrodkowałem również search na tabletach, zmniejszyłem height containera tereaz nie ma pionowych odstępów.

2021-04-17 14:28 UTC, kamilwilk95 requested changes
![image](https://user-images.githubusercontent.com/26415481/115116474-ea05e680-9f99-11eb-851c-143e9a5da436.png)

2021-04-17 18:29 UTC, stiffelbo commented
Dzięki za wskazówki. Usunąłem sztywne wymiarowanie wierszy w menuBar, zamiast tego dodałem $base-padding, z wyjątkiem tabletów gdzie search i menu układają się w dwóch wierszach. mam nadzieje ze jest ok.

2021-04-18 08:55 UTC, kamilwilk95 submitted a review, later dismissed
Jest ok, jeszcze konflikty

2021-04-19 05:21 UTC, kamilwilk95 approved these changes

2021-04-19 05:21 UTC, merged