Wdp210402 17
kamilwilk95/wdp-2104-02 pull request #21
Opened 2021-04-19 18:58 UTC by stiffelbo

Daj znać proszę jak ci się to widzi. Dzięki.

2021-04-19 19:32 UTC, kamilwilk95 requested changes
Najpierw musi być zmergowane compare bo ten task wyszedł z compare

2021-04-19 19:40 UTC, stiffelbo commented
$ git commit -m "merge WDP210402-17"
husky > pre-commit (node v10.23.3)
No staged files match any of provided globs.
On branch WDP210402-12
Your branch is up to date with 'origin/WDP210402-12'.

nothing to commit, working tree clean

2021-04-20 19:56 UTC, stiffelbo commented
zaktualizowałem do mastera po pulu taska *-12. wypchnięte

2021-04-21 05:52 UTC, kamilwilk95 approved these changes

2021-04-21 05:52 UTC, merged