Wdp210402 10
kamilwilk95/wdp-2104-02 pull request #4
Opened 2021-04-14 14:29 UTC by RezaiMartyna

2021-04-14 17:06 UTC, kamilwilk95 requested changes

2021-04-14 17:06 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.js
> +      <ol>
`ol` to lista numerowana, lepiej użyć `ul` ;)

2021-04-14 17:06 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      float:left;
zamiast `float` może lepiej użyć position absolute i to ustawić względem relatywnego rodzica? To też powinno rozwiązać aktualny problem skakania całej sekcji.

2021-04-14 17:06 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    ol > li:hover > ul {
Ten selektor i 54 oraz 57 można zgrupować i inne też ;)

2021-04-14 17:06 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    ol > li > ul > li {
Ogólnie te `>` nie są raczej konieczne ;)

2021-04-15 17:33 UTC, RezaiMartyna commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    ol > li:hover > ul {
zrobione

2021-04-15 20:18 UTC, kamilwilk95 requested changes

2021-04-15 20:18 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +            &:hover {
hover lepiej nasłuchiwać na ul które jest na najwyższym poziomie lub pozmieniać style. Aktualnie po najechaniu, tło nie jest na całym elemencie a jedynie na środku zostawiając białe odstępu po prawej i lewej stronie. Może niech pierwsze ul nie ma puddingu i marginesu.

Musisz też poprawić style elementy search obok dropdown, bo teraz jest krzywo i ma obramowanie, na masterze wygląda ok.

Master:
![image](https://user-images.githubusercontent.com/26415481/114932928-62549680-9e38-11eb-9118-19c32206fb6a.png)

task 10
![image](https://user-images.githubusercontent.com/26415481/114933000-77c9c080-9e38-11eb-82b4-a805a63716ae.png)

2021-04-15 20:58 UTC, RezaiMartyna commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +            &:hover {
zrobione

2021-04-16 05:12 UTC, kamilwilk95 submitted a review, later dismissed

2021-04-16 05:12 UTC, kamilwilk95 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +
Ta pusta linia jest niepotrzebna

2021-04-16 11:35 UTC, kamilwilk95 approved these changes, later dismissed

2021-04-16 11:36 UTC, kamilwilk95 approved these changes

2021-04-16 11:36 UTC, merged