Wdp210402 29
kamilwilk95/wdp-2104-02 pull request #42
Opened 2021-04-30 18:42 UTC by RezaiMartyna

2021-05-01 13:18 UTC, MarcinPytlak requested changes
Hej, sorka że w jednym zbiorczym komentarzu, ale nie wiem jak się robi komentarze z zaznaczeniem kodu :D 
nie wiem jak u Ciebie, ale u mnie mam następujące błędy: zdublowane deklarację configReducer oraz commentsReducer w store.js;
 - dubel ikonek fa w productbox.js;
 - 2 brakujące przecinki w initialstate oraz jeden błąd wyrównania linii również w tym store,
 
 Odnośnie działania RWD na galerii, to nie wiem jak u Ciebie, ale u mnie to zdjęcie statyczne z prawej strony zupełnie znika :( chyba, że znowu coś ja sknociłem to przepraszam :)

2021-05-01 19:26 UTC, MarcinPytlak submitted a review, later dismissed

2021-05-01 20:57 UTC, kamilwilk95 requested changes
![image](https://user-images.githubusercontent.com/26415481/116794784-152b2280-aad0-11eb-8311-35d0c6d46ea0.png)

Zdjęcie po prawej stronie jest za wcześnie chowane, miało być na telefonach a jest też na tabletach.

Nie wiedzę aby była możliwość przewijania miniaturek za pomocą Swipeable

2021-05-01 20:57 UTC, kamilwilk95 commented on src/components/features/BrandMarks/BrandMarks.js
> +    return <h3 className={styles.title}>Brand Marks</h3>;
Co to za komponent?

2021-05-02 17:02 UTC, kamilwilk95 requested changes
![image](https://user-images.githubusercontent.com/26415481/116821095-c4233900-ab78-11eb-9671-db720ae251ae.png)
![image](https://user-images.githubusercontent.com/26415481/116821144-f765c800-ab78-11eb-9724-65dd66607fa5.png)

2021-05-03 07:49 UTC, kamilwilk95 requested changes
`Slider miniaturek powinno dać się przewijać również za pomocą komponentu Swipeable` nie widzę fragmentu za to odpowiedzialnego? W zadaniu jest opis co w przypadku jak nie ma jeszcze Swipeable w Galerii.

2021-05-03 07:49 UTC, kamilwilk95 commented on src/components/common/socialMedia/socialMedia.js
> +const SocialMedia = () => (
Skąd to się wzieło na tym branchu??

2021-05-04 18:52 UTC, kamilwilk95 requested changes

2021-05-04 18:52 UTC, kamilwilk95 commented on src/components/common/socialMedia/socialMedia.js
> +import React from 'react';
Nazwy plików z dużej litery, wywala błąd, projekt się nie uruchamia

2021-05-04 18:54 UTC, kamilwilk95 approved these changes

2021-05-04 18:57 UTC, merged