add media: hide product box, gallety box: center, resize fonts
kamilwilk95/wdp-2104-02 pull request #44
Opened 2021-05-01 16:39 UTC by stiffelbo

Dodane reguły media

2021-05-01 19:18 UTC, MarcinStarzynski requested changes
@stiffelbo mógłbyś rzucić okiem na to zadanie? W tasku na jirze jest napisane o dodaniu komponentu Swipeable na galerię. Dzięki :D

2021-05-02 10:00 UTC, stiffelbo commented
Dodałem troche styli oraz Swipable na galerie. Narazie działa tak że po swipie wywala strone :)

2021-05-02 10:31 UTC, stiffelbo commented
event handler na swipe posprzątany.

2021-05-02 10:41 UTC, MarcinStarzynski approved these changes
Sprawdzone i działa :D

2021-05-02 12:31 UTC, kamilwilk95 approved these changes

2021-05-02 12:31 UTC, merged