Wdp210402 36
kamilwilk95/wdp-2104-02 pull request #45
Opened 2021-05-01 19:58 UTC by stiffelbo

Dodałem linkowanie do stronyProduktu do guzika QUICK VIEW w productBox, dodałem również linkowanie do HOME by było jak wrócić :)

2021-05-02 17:38 UTC, RezaiMartyna commented on src/components/views/ProductPage/ProductPage.js
> +          <div className={`col-md-6`}>
czy nie lepiej byłoby  col-md-5 a drugi col-md-7 ? chyba one nie powinny być równe?

2021-05-02 17:59 UTC, stiffelbo commented
Wygląda na to ze taki podział jest bliżej tego co w PSD :) dzieki.

2021-05-02 17:59 UTC, stiffelbo commented on src/components/views/ProductPage/ProductPage.js
> +          <div className={`col-md-6`}>
Poprawione, dzieki :)

2021-05-02 18:19 UTC, RezaiMartyna submitted a review, later dismissed

2021-05-02 19:56 UTC, kamilwilk95 requested changes
![image](https://user-images.githubusercontent.com/26415481/116825777-03f61a80-ab91-11eb-93c3-a32c21c03b9a.png)

Nie jestem pewien czy to zepsuło się tutaj ale jak jest bug to go od razu poprawmy

2021-05-02 20:37 UTC, stiffelbo commented
U mnie się napsuło ale poprawiłem, zobacz proszę czy już jest ok.

2021-05-02 21:17 UTC, stiffelbo commented
kolory tekstu w guzikach poprawione

2021-05-03 07:55 UTC, kamilwilk95 requested changes
Poprawione co zgłosiłem ostatnio, ale teraz na stronie np. http://localhost:3000/product/aenean-ru-bristique-7 w około produktu i placeholderu na dane jakieś dziwne i niepotrzebne obramowanie się pojawiło

2021-05-03 08:14 UTC, stiffelbo commented
Ramki usunięte

2021-05-03 12:00 UTC, kamilwilk95 approved these changes

2021-05-03 12:00 UTC, merged