Wdp210402 38
kamilwilk95/wdp-2104-02 pull request #49
Opened 2021-05-02 16:17 UTC by RezaiMartyna

2021-05-02 16:28 UTC, MarcinPytlak reviewed
Hej, niestety zaplątały się tutaj również zmiany z poprzednich zadań, Kamil czy to można bezpiecznie mergować? :) jeżeli tak, to ikonki wyglądają spoko :)

2021-05-02 18:29 UTC, stiffelbo requested changes

2021-05-02 18:29 UTC, stiffelbo commented on src/components/common/socialMedia/socialMedia.js
> +import React from 'react';
zmień nazwe folderu i pliku na /SocialMedia/SocialMedia.js

2021-05-02 18:29 UTC, stiffelbo commented on src/components/common/socialMedia/socialMedia.module.scss
> +@import "../../../styles/settings.scss";
zmień nazwę folderu i pliku na /SocialMedia/SocialMedia.module.scss,
import w SocialMedia.js masz ok wtedy :)

2021-05-03 16:50 UTC, stiffelbo submitted a review, later dismissed

2021-05-04 18:31 UTC, MarcinPytlak submitted a review, later dismissed
Hej, widziałem, ikonki wyglądają spoko :)

2021-05-04 20:18 UTC, kamilwilk95 submitted a review, later dismissed

2021-05-05 04:52 UTC, kamilwilk95 approved these changes

2021-05-05 04:52 UTC, merged