Wdp210402 4
kamilwilk95/wdp-2104-02 pull request #5
Opened 2021-04-14 14:30 UTC by RezaiMartyna

2021-04-14 14:39 UTC, kamilwilk95 requested changes

2021-04-14 14:39 UTC, kamilwilk95 commented on src/components/common/Button/Button.module.scss
> +
Tej wolnej linii nie powinno tutaj być ;)

2021-04-14 14:39 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBox.module.scss
> +.root:hover .buttons {
To chyba to samo co w linii 83

2021-04-14 14:39 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBox.module.scss
> +.root:hover .buttonPrice  {
to można zapisać wyżej aby nie powtarzać `.root`

2021-04-14 15:04 UTC, RezaiMartyna commented on src/components/common/ProductBox/ProductBox.module.scss
> +.root:hover .buttons {
poprawione :)

2021-04-14 15:05 UTC, RezaiMartyna commented on src/components/common/Button/Button.module.scss
> +
poprawione :)

2021-04-16 16:46 UTC, kamilwilk95 approved these changes

2021-04-16 16:48 UTC, merged